import time

print("=" * 44)
print("  Chat with My Notes — Query Demo")
print("=" * 44)
print()
print("  QUERY (italiano)")
print("  Quali sono le mie spese tecnologiche")
print("  fisse annuali per il lavoro?")
print()
time.sleep(3)

print("  RETRIEVAL — Bilingual Fusion (BRF)")
print("  1. minsearch  ← query ITA")
print("  2. translate  → ENG  (gemma4:e4b)")
print("  3. minsearch  ← query ENG")
print("  4. RRF fusion k=60   (ITA + ENG)")
print("  5. semantic   ← nomic-embed-text")
print("  6. final RRF  (BRF + Semantic)")
print()
time.sleep(4)

print("  ANSWER")
print("  Le spese tecnologiche fisse annuali")
print("  includono abbonamenti software,")
print("  hardware di sviluppo e servizi cloud.")
time.sleep(3)

print()
print("  SOURCES")
print("  1. export_Notion_Varie_24052026.md")
print("  2. export_Notion_61E62_24052026.md")
print("  Generator: gemma4:8k-latest  Minisforum")
print("  Judge    : gemma4:e4b        Asus F15")
print("  Total    : 65.9s")
#print("=" * 44)